name: cv-prince
channels:
    - conda-forge
dependencies:
    - python
    - pip
    - numpy
    - matplotlib
    - jupyter
    - opencv
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - imageio
    - sympy
    - pip:
        - moviepy
        - tensorflow==1.13.1
        - git+https://github.com/fchollet/keras.git
